2024-02-12 20:22:06,574 INFO    StreamThr :66813 [internal.py:wandb_internal():86] W&B internal server running at pid: 66813, started at: 2024-02-12 20:22:06.572921
2024-02-12 20:22:06,577 DEBUG   HandlerThread:66813 [handler.py:handle_request():146] handle_request: status
2024-02-12 20:22:06,585 INFO    WriterThread:66813 [datastore.py:open_for_write():87] open: /home-nfs/fx2024/NLP/NLP/wandb/run-20240212_202206-test/run-test.wandb
2024-02-12 20:22:06,587 DEBUG   SenderThread:66813 [sender.py:send():382] send: header
2024-02-12 20:22:06,600 DEBUG   SenderThread:66813 [sender.py:send():382] send: run
2024-02-12 20:22:06,744 ERROR   SenderThread:66813 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 20:22:06,745 ERROR   SenderThread:66813 [internal_api.py:execute():374] {"errors":[{"message":"run fayxu/test-project/test was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 20:22:08,037 ERROR   SenderThread:66813 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 20:22:08,037 ERROR   SenderThread:66813 [internal_api.py:execute():374] {"errors":[{"message":"run fayxu/test-project/test was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 20:22:10,317 ERROR   SenderThread:66813 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 20:22:10,317 ERROR   SenderThread:66813 [internal_api.py:execute():374] {"errors":[{"message":"run fayxu/test-project/test was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 20:22:10,318 INFO    SenderThread:66813 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home-nfs/fx2024/mc3/envs/fei-venv/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-nfs/fx2024/mc3/envs/fei-venv/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-nfs/fx2024/mc3/envs/fei-venv/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-nfs/fx2024/mc3/envs/fei-venv/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-nfs/fx2024/mc3/envs/fei-venv/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home-nfs/fx2024/mc3/envs/fei-venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-02-12 20:22:11,602 DEBUG   HandlerThread:66813 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:22:14,833 ERROR   SenderThread:66813 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 20:22:14,833 ERROR   SenderThread:66813 [internal_api.py:execute():374] {"errors":[{"message":"run fayxu/test-project/test was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 20:22:16,604 DEBUG   HandlerThread:66813 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:22:21,605 DEBUG   HandlerThread:66813 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:22:24,303 ERROR   SenderThread:66813 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 20:22:24,303 ERROR   SenderThread:66813 [internal_api.py:execute():374] {"errors":[{"message":"run fayxu/test-project/test was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 20:22:26,607 DEBUG   HandlerThread:66813 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:22:31,608 DEBUG   HandlerThread:66813 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:22:36,610 DEBUG   HandlerThread:66813 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:22:41,612 DEBUG   HandlerThread:66813 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:22:43,540 ERROR   SenderThread:66813 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 20:22:43,540 ERROR   SenderThread:66813 [internal_api.py:execute():374] {"errors":[{"message":"run fayxu/test-project/test was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 20:22:46,614 DEBUG   HandlerThread:66813 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:22:51,615 DEBUG   HandlerThread:66813 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:22:56,617 DEBUG   HandlerThread:66813 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:23:01,619 DEBUG   HandlerThread:66813 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:23:06,620 DEBUG   HandlerThread:66813 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:23:11,622 DEBUG   HandlerThread:66813 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:23:16,624 DEBUG   HandlerThread:66813 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:23:19,935 ERROR   SenderThread:66813 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 20:23:19,936 ERROR   SenderThread:66813 [internal_api.py:execute():374] {"errors":[{"message":"run fayxu/test-project/test was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 20:23:21,626 DEBUG   HandlerThread:66813 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:23:26,627 DEBUG   HandlerThread:66813 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:23:31,629 DEBUG   HandlerThread:66813 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:23:36,631 DEBUG   HandlerThread:66813 [handler.py:handle_request():146] handle_request: cancel
2024-02-12 20:23:36,631 DEBUG   HandlerThread:66813 [handler.py:handle_request():146] handle_request: cancel
2024-02-12 20:23:36,632 DEBUG   SenderThread:66813 [sender.py:send():391] Record cancelled: run
2024-02-12 20:23:36,632 DEBUG   HandlerThread:66813 [handler.py:handle_request():146] handle_request: status_report
2024-02-12 20:23:36,762 DEBUG   HandlerThread:66813 [handler.py:handle_request():146] handle_request: shutdown
2024-02-12 20:23:36,762 INFO    HandlerThread:66813 [handler.py:finish():869] shutting down handler
2024-02-12 20:23:37,633 INFO    SenderThread:66813 [sender.py:finish():1572] shutting down sender
2024-02-12 20:23:37,633 INFO    WriterThread:66813 [datastore.py:close():296] close: /home-nfs/fx2024/NLP/NLP/wandb/run-20240212_202206-test/run-test.wandb
