2024-02-12 20:35:21,869 INFO    StreamThr :69546 [internal.py:wandb_internal():86] W&B internal server running at pid: 69546, started at: 2024-02-12 20:35:21.868034
2024-02-12 20:35:21,872 DEBUG   HandlerThread:69546 [handler.py:handle_request():146] handle_request: status
2024-02-12 20:35:21,876 INFO    WriterThread:69546 [datastore.py:open_for_write():87] open: /home-nfs/fx2024/NLP/NLP/wandb/run-20240212_203521-test/run-test.wandb
2024-02-12 20:35:21,879 DEBUG   SenderThread:69546 [sender.py:send():382] send: header
2024-02-12 20:35:21,892 DEBUG   SenderThread:69546 [sender.py:send():382] send: run
2024-02-12 20:35:22,040 ERROR   SenderThread:69546 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 20:35:22,040 ERROR   SenderThread:69546 [internal_api.py:execute():374] {"errors":[{"message":"run fayxu/test-project/test was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 20:35:23,298 ERROR   SenderThread:69546 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 20:35:23,299 ERROR   SenderThread:69546 [internal_api.py:execute():374] {"errors":[{"message":"run fayxu/test-project/test was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 20:35:25,392 ERROR   SenderThread:69546 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 20:35:25,393 ERROR   SenderThread:69546 [internal_api.py:execute():374] {"errors":[{"message":"run fayxu/test-project/test was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 20:35:25,393 INFO    SenderThread:69546 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home-nfs/fx2024/mc3/envs/fei-venv/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-nfs/fx2024/mc3/envs/fei-venv/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-nfs/fx2024/mc3/envs/fei-venv/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-nfs/fx2024/mc3/envs/fei-venv/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-nfs/fx2024/mc3/envs/fei-venv/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home-nfs/fx2024/mc3/envs/fei-venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-02-12 20:35:26,894 DEBUG   HandlerThread:69546 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:35:29,540 ERROR   SenderThread:69546 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 20:35:29,540 ERROR   SenderThread:69546 [internal_api.py:execute():374] {"errors":[{"message":"run fayxu/test-project/test was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 20:35:31,896 DEBUG   HandlerThread:69546 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:35:36,897 DEBUG   HandlerThread:69546 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:35:37,645 ERROR   SenderThread:69546 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 20:35:37,645 ERROR   SenderThread:69546 [internal_api.py:execute():374] {"errors":[{"message":"run fayxu/test-project/test was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 20:35:41,899 DEBUG   HandlerThread:69546 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:35:46,901 DEBUG   HandlerThread:69546 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:35:51,903 DEBUG   HandlerThread:69546 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:35:54,726 ERROR   SenderThread:69546 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 20:35:54,727 ERROR   SenderThread:69546 [internal_api.py:execute():374] {"errors":[{"message":"run fayxu/test-project/test was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 20:35:56,905 DEBUG   HandlerThread:69546 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:36:01,907 DEBUG   HandlerThread:69546 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:36:06,908 DEBUG   HandlerThread:69546 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:36:11,910 DEBUG   HandlerThread:69546 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:36:16,912 DEBUG   HandlerThread:69546 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:36:21,914 DEBUG   HandlerThread:69546 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:36:26,915 DEBUG   HandlerThread:69546 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:36:31,917 DEBUG   HandlerThread:69546 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:36:33,551 ERROR   SenderThread:69546 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 20:36:33,551 ERROR   SenderThread:69546 [internal_api.py:execute():374] {"errors":[{"message":"run fayxu/test-project/test was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 20:36:36,919 DEBUG   HandlerThread:69546 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:36:41,921 DEBUG   HandlerThread:69546 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:36:46,923 DEBUG   HandlerThread:69546 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 20:36:51,925 DEBUG   HandlerThread:69546 [handler.py:handle_request():146] handle_request: cancel
2024-02-12 20:36:51,925 DEBUG   HandlerThread:69546 [handler.py:handle_request():146] handle_request: cancel
2024-02-12 20:36:51,926 DEBUG   SenderThread:69546 [sender.py:send():391] Record cancelled: run
2024-02-12 20:36:51,926 DEBUG   HandlerThread:69546 [handler.py:handle_request():146] handle_request: status_report
2024-02-12 20:36:52,096 DEBUG   HandlerThread:69546 [handler.py:handle_request():146] handle_request: shutdown
2024-02-12 20:36:52,096 INFO    HandlerThread:69546 [handler.py:finish():869] shutting down handler
2024-02-12 20:36:52,926 INFO    SenderThread:69546 [sender.py:finish():1572] shutting down sender
2024-02-12 20:36:52,927 INFO    WriterThread:69546 [datastore.py:close():296] close: /home-nfs/fx2024/NLP/NLP/wandb/run-20240212_203521-test/run-test.wandb
